name: vitest

on:
  push:

jobs:
  test:
    name: Run test codes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run Vitest
        run: npx vitest --coverage.enabled true
      - name: Show coverage
        uses: davelosert/vitest-coverage-report-action@v2